### ISSUE TITLE
Android Layout change issue

### ISSUE THREAD

**Issue by stanicavuleta** [WrathChaos/react-native-redux-boilerplate#341]
Hi
Everybody.
I developed one project.
This project is run good in the debug mode.
But this project is changed in layout(LinearLayout) when I build the release version.
How can I fix this error?
Thank you for your replying. :)

**Comment by WrathChaos** [comment]
Hello @stanicavuleta,

You should open a question on StackoverFlow. Also, you did not even put a screenshot or any other code to let people help you. You need to add more details about the question :)

Good luck!
